// import { StyleSheet, Dimensions } from "react-native";
// import {
//   responsiveFontSize,
//   responsiveWidth,
//   responsiveHeight,
// } from "react-native-responsive-dimensions";
// const primaryColor = "#56BC1F";
// const secondaryColor = "gray";
// const dangerColor = "#BC1F1F";
// const whiteColor = "white";
// const lightGray = "#f5f5f5";
// const { width, height } = Dimensions.get('screen');

// const styles = StyleSheet.create({
//   container: {
//     flex: 1,
//     backgroundColor: whiteColor,
//   },

//   //bording
//   rectangleContainer: {
//     flexDirection: "row",
//   },
//   rectangle: {
//     marginTop: responsiveHeight(10),
//     right: 70,
//     backgroundColor: "#D9D9D945",
//     width: responsiveWidth(80),
//     height: responsiveWidth(80),
//     borderRadius: responsiveWidth(40),
//   },
//   image: {
//     right: responsiveWidth(75),
//     top: responsiveHeight(10),
//     width: responsiveWidth(80),
//     height: responsiveWidth(80),
//   },
//   content: {
//     justifyContent: "center",
//     alignItems: "center",
//     marginTop: responsiveHeight(4),
//   },
//   headingtext: {
//     color: primaryColor,
//     fontSize: width * 0.076,
//     letterSpacing: 0.3,
//     fontFamily: "ExtraBold",
//   },
//   paratext: {
//     marginTop: responsiveHeight(1),
//     fontSize: width * 0.034,
//     textAlign: "center",
//     paddingHorizontal: 30,
//     lineHeight: 20,
//     fontFamily: "Regular",
//   },
//   dotcontainer: {
//     marginTop: responsiveHeight(12),
//     marginBottom: responsiveHeight(5),
//     flexDirection: "row",
//     justifyContent: "center",
//     alignItems: "center",
//   },
//   dot: {
//     width: 10,
//     height: 10,
//     borderRadius: 100,
//     backgroundColor: "#e6e6e6",
//     marginHorizontal: 5,
//   },
//   active: {
//     backgroundColor: primaryColor,
//     color: whiteColor,
//   },
//   btngroup: {
//     marginHorizontal: 10,
//     flexDirection: "row",
//     justifyContent: "space-evenly",
//     alignItems: "center",
//     marginTop: responsiveHeight(8),
//   },
//   btntext: {
//     color: primaryColor,
//     letterSpacing: 1,
//     paddingVertical: 10,
//     paddingHorizontal: 50,
//     borderRadius: 10,
//     fontFamily: "SemiBold",
//   },
//   btnactive: {
//     borderRadius: 10,
//     shadowColor: primaryColor,
//     shadowOffset: { width: 1, height: 1, blur: 8 },
//     shadowOpacity: 0.4,
//     shadowRadius: 3,
//     elevation: 5,
//   },
//   fullbtn: {
//     fontFamily: "SemiBold",
//     letterSpacing: 1,
//     paddingVertical: 10,
//     paddingHorizontal: 110,
//     borderRadius: 10,
//   },

//   //login/registration
//   loginHead: {
//     flexDirection: "row",
//     justifyContent: "space-around",
//     alignItems: "center",
//     paddingTop: responsiveHeight(2),
//     paddingBottom: responsiveHeight(2),
//   },
//   loginHeadText: {
//     // paddingLeft: responsiveWidth(15),
//     paddingLeft: width * 0.12,
//     marginTop: responsiveHeight(7),
//     fontFamily: "Bold",
//   },
//   desctext: {
//     fontSize: 14,
//     lineHeight: responsiveHeight(2),
//     fontFamily: "Regular",
//   },
//   loginimag: {
//     height: 200,
//     width: 160,
//   },
//   form: {
//     marginHorizontal: responsiveWidth(8),
//   },
//   inputfield: {
//     marginBottom: responsiveHeight(2.2),
//   },
//   label: {
//     fontSize: 15,
//     marginBottom: responsiveHeight(1),
//     fontFamily: "Regular",
//   },
//   input: {
//     paddingVertical: responsiveHeight(1.5),
//     paddingHorizontal: responsiveWidth(5),
//     backgroundColor: lightGray,
//     fontSize: 15,
//     fontFamily: "Regular",
//     borderRadius: 5,
//   },
//   agreegroup: {
//     flexDirection: "row",
//     justifyContent: "flex-start",
//     alignItems: "flex-end",
//     marginRight: 20,
//   },
//   onlybtn: {
//     padding: responsiveHeight(1.3),
//     display: "flex",
//     justifyContent: "center",
//     alignItems: "center",
//     backgroundColor: primaryColor,
//     borderRadius: responsiveWidth(1),
//     marginBottom: responsiveHeight(1),
//     shadowColor: primaryColor,
//     shadowOffset: { width: 9, height: 9 },
//     shadowOpacity: 1,
//     shadowRadius: 3,
//     elevation: 5,
//   },
//   onlybtntext: {
//     color: whiteColor,
//     fontSize: 17,
//     letterSpacing: 0.5,
//     fontFamily: "Bold",
//   },
//   bottom: {
//     flexDirection: "row",
//     justifyContent: "center",
//     alignItems: "flex-end",
//     paddingTop: responsiveHeight(4),
//   },
//   link: {
//     color: primaryColor,
//     fontFamily: "Regular",
//   },
//   loginimag2: {
//     height: responsiveHeight(30),
//     marginRight: responsiveWidth(6),
//     width: responsiveWidth(50),
//     top: responsiveHeight(4),
//   },
//   //body parts
//   flatlistheader: {
//     paddingTop: responsiveHeight(4),
//     paddingHorizontal: responsiveWidth(8),
//     paddingBottom: responsiveHeight(2),
//   },
//   headername: {
//     flexDirection: "row",
//     justifyContent: "space-between",
//     alignItems: "center",
//   },
//   headernametext: {
//     fontSize: width * 0.074,
//     fontFamily: "Medium",
//   },
//   bodypartsbox: {
//     paddingVertical: responsiveHeight(0.5),
//     paddingHorizontal: responsiveHeight(0.1),
//   },
//   bodypartsboxshadow: {
//     flexDirection: "row",
//     justifyContent: "space-between",
//     paddingVertical: responsiveHeight(1),
//     paddingHorizontal: responsiveHeight(1.6),
//     borderRadius: 6,
//     backgroundColor: whiteColor,
//     elevation: 1.5,
//     shadowOffset: { width: 5, height: 5, blur: 10 },
//     shadowOpacity: 1,
//     shadowRadius: 3,
//     shadowColor: secondaryColor,
//   },
//   bodypartsboxtext: {
//     fontFamily: "Regular",
//     fontSize: responsiveFontSize(2.1),
//   },
//   rightsidebox: {
//     flexDirection: "row",
//     paddingTop: responsiveHeight(0.5),
//   },
//   //modal
//   viewWrapper: {
//     flex: 1,
//     flexDirection: "row",
//     alignItems: "center",
//     justifyContent: "center",
//     backgroundColor: "rgba(0, 0, 0, 0.2)",
//   },
//   modalView: {
//     alignItems: "flex-start",
//     justifyContent: "center",
//     position: "absolute",
//     width: "80%",
//     elevation: 5,
//     backgroundColor: whiteColor,
//     borderRadius: 7,
//     paddingVertical: responsiveHeight(2),
//     paddingHorizontal: responsiveHeight(2),
//   },
//   modellabel: {
//     fontSize: responsiveFontSize(2.1),
//     opacity: 0.5,
//     fontFamily: "Regular",
//   },
//   modalinput: {
//     width: "100%",
//     borderRadius: 5,
//     paddingVertical: responsiveHeight(1),
//     paddingHorizontal: responsiveHeight(1.6),
//     borderColor: "rgba(0, 0, 0, 0.2)",
//     borderWidth: 1,
//     marginVertical: responsiveHeight(1.4),
//     fontFamily: "Regular",
//   },

//   modelAlertbtn: {
//     paddingVertical: responsiveHeight(1),
//     paddingHorizontal: responsiveWidth(2),
//     borderRadius: responsiveWidth(1.5),
//     backgroundColor: primaryColor,
//     flex: 1,
//     flexDirection: "row",
//     justifyContent: "flex-end",
//     alignItems: "center",
//   },

//   //addcomponent
//   addmaincontainer: {
//     position: "absolute",
//     bottom: responsiveWidth(8),
//     right: responsiveWidth(8),
//     zIndex: 1000,
//     shadowColor: secondaryColor,
//     shadowOffset: {
//       width: 0,
//       height: 18,
//     },
//     shadowOpacity: 0.3,
//     shadowRadius: 20,
//     elevation: 24,
//   },
//   innercontainer: {
//     backgroundColor: primaryColor,
//     height: 60,
//     width: 60,
//     borderRadius: 100,
//     position: "relative",
//     flexDirection: "row",
//     justifyContent: "center",
//     alignItems: "center",
//   },

//   //shop profile css start
//   protop: {
//     height: responsiveHeight(33),
//     backgroundColor: lightGray,
//     display: "flex",
//     justifyContent: "center",
//     alignItems: "center",
//   },
//   profilepic: {
//     width: responsiveWidth(30),
//     height: responsiveWidth(30),
//     borderRadius: responsiveWidth(15),
//   },
//   profilelater: {
//     width: responsiveWidth(30),
//     height: responsiveWidth(30),
//     borderRadius: responsiveWidth(15),
//     backgroundColor: primaryColor,
//     display: "flex",
//   },
//   profileTitle: {
//     marginTop: responsiveHeight(2),
//     fontFamily: "Regular",
//     fontSize: responsiveFontSize(2.2),
//   },
//   titletext: {
//     fontSize: responsiveFontSize(2.4),
//     fontFamily: "Medium",
//     marginTop: responsiveHeight(1),
//   },
//   spacebetween: {
//     flexDirection: "row",
//     justifyContent: "space-between",
//     alignItems: "center",
//     marginVertical: responsiveHeight(2),
//   },
//   flexstart: {
//     flexDirection: "row",
//     justifyContent: "flex-start",
//     alignItems: "center",
//   },
//   backPRofileIcon: {
//     backgroundColor: lightGray,
//   },
//   proicon: {
//     backgroundColor: lightGray,
//     paddingHorizontal: responsiveWidth(3),
//     paddingVertical: responsiveWidth(3),
//     borderRadius: responsiveWidth(1.5),
//     marginRight: responsiveWidth(5),
//   },
//   prolistfont: {
//     fontSize: responsiveFontSize(2.3),
//     fontFamily: "Regular",
//   },

//   //edit profile css start
//   profilelEditAvtar: {
//     width: responsiveWidth(30),
//     height: responsiveWidth(30),
//     borderRadius: responsiveWidth(15),
//     backgroundColor: lightGray,
//     borderColor: primaryColor,
//     borderWidth: 2.5,
//     borderStyle: "dashed",
//   },
//   profilecameraicon: {
//     textAlign: "center",
//     fontSize: responsiveFontSize(2),
//     backgroundColor: "black",
//     color: "gray",
//     marginTop: responsiveHeight(2),
//     width: "20%",
//     borderColor: "none",
//     borderWidth: 0,
//     borderRadius: responsiveWidth(3),
//     padding: responsiveHeight(0.3),
//     position: "absolute",
//     bottom: responsiveHeight(-1.5),
//     left: responsiveWidth(11.5),
//   },

//   //customer
//   customerMain: {
//     flex: 0,
//     flexDirection: "row",
//     justifyContent: "space-between",
//     alignItems: "center",
//     borderBottomColor: "#0000001A",
//     paddingBottom: responsiveHeight(2),
//     borderBottomWidth: 1,
//     marginTop: responsiveHeight(2),
//   },
//   customerProfileImage: {
//     width: responsiveWidth(12),
//     height: responsiveWidth(12),
//     borderRadius: responsiveWidth(15),
//   },
//   customerName: {
//     fontSize: width * 0.048,
//     fontFamily: "Medium",
//   },
//   headerwithline: {
//     paddingTop: responsiveHeight(3),
//     paddingBottom: responsiveHeight(1),
//   },
//   line70: {
//     borderWidth: 0.5,
//     borderColor: secondaryColor,
//     width: responsiveWidth(60),
//     marginLeft: responsiveWidth(20),
//   },

//   //dress
//   dressContainermain: {
//     flexDirection: "row",
//     flexWrap: "wrap",
//     gap: responsiveWidth(3),
//     paddingHorizontal: responsiveWidth(8),
//     paddingBottom: responsiveHeight(2),
//   },
//   dressFlatListContainermain: {
//     paddingHorizontal: responsiveWidth(8),
//     paddingBottom: responsiveHeight(2),
//   },
//   dressContainer: {
//     backgroundColor: whiteColor,
//     elevation: 1.5,
//     shadowOffset: { width: 5, height: 5, blur: 10 },
//     shadowOpacity: 1,
//     shadowRadius: 3,
//     shadowColor: secondaryColor,
//     width: responsiveWidth(26),
//     paddingTop: responsiveWidth(3),
//     paddingHorizontal: responsiveHeight(1),
//     borderRadius: 6,
//   },
//   imageContainer: {
//     borderRadius: 6,
//     backgroundColor: lightGray,
//     flex: 0,
//     justifyContent: "center",
//     alignItems: "center",
//     marginBottom: responsiveHeight(0.6),
//   },
//   dressfileSelect: {
//     width: responsiveWidth(6),
//     height: responsiveHeight(13),
//     borderColor: secondaryColor,
//     borderWidth: 2,
//     width: responsiveWidth(84),
//     borderRadius: 4,
//     borderStyle: "dashed",
//     flex: 0,
//     justifyContent: "center",
//     alignItems: "center",
//     flexDirection: "row",
//   },
//   dressfileSelecttext: {
//     fontFamily: "Regular",
//     fontSize: responsiveFontSize(2),
//   },
//   dressbodypartsselected: {
//     backgroundColor: primaryColor,
//     width: responsiveWidth(5.4),
//     height: responsiveHeight(2.6),
//     flex: 0,
//     alignItems: "center",
//     borderRadius: 100,
//     position: "absolute",
//     justifyContent: "center",
//     right: 0,
//   },
//   dressPartsdropdownMenu: {
//     backgroundColor: whiteColor,
//     width: responsiveWidth(37),
//     borderRadius: 8,
//     paddingHorizontal: 10,
//     paddingVertical: 4,
//     shadowColor: "#000",
//     shadowOffset: {
//       width: 0,
//       height: 2,
//     },
//     shadowOpacity: 0.25,
//     shadowRadius: 3.84,
//     elevation: 5,
//     position: "absolute",
//     top: responsiveHeight(8),
//     right: responsiveWidth(4),
//   },
//   dressPartsdropdownItem: {
//     paddingVertical: responsiveHeight(1),
//   },
//   dressPartsdropdownItemText: {
//     fontSize: responsiveFontSize(2),
//     fontFamily: "Regular",
//   },
//   //dressmodal
//   modelicon: {
//     display: "flex",
//     flexDirection: "row",
//     justifyContent: "center",
//     alignItems: "center",
//     width: responsiveWidth(80),
//     paddingVertical: responsiveHeight(3),
//   },
//   modelAlertlabel: {
//     fontSize: responsiveFontSize(3),
//     opacity: 0.7,
//     textAlign: "center",
//     width: responsiveWidth(80),
//     marginTop: 5,
//   },
//   modelalertdec: {
//     fontSize: responsiveFontSize(2.3),
//     marginHorizontal: responsiveWidth(10),
//     opacity: 0.6,
//     textAlign: "center",
//     width: responsiveWidth(60),
//   },

//   //measurement
//   measurementSmallTitleMain: {
//     marginHorizontal: responsiveWidth(8),
//     marginTop: responsiveHeight(2),
//   },
//   measurementSmallTitle: {
//     color: secondaryColor,
//     fontSize: responsiveFontSize(1.5),
//     fontFamily: "Regular",
//   },

//   measurementcateLine: {
//     borderWidth: 0.2,
//     borderColor: "#9f9f9f",
//     width: responsiveWidth(30),
//     marginTop: responsiveHeight(1),
//   },
//   measurementKurtaImageMain: {
//     width: responsiveWidth(10.5),
//     height: responsiveHeight(5),
//     backgroundColor: "#F2F2F2",
//     flex: 0,
//     justifyContent: "center",
//     alignItems: "center",
//     borderWidth: 0,
//     borderRadius: responsiveHeight(1),
//   },
//   measurementkurtaImage: {
//     width: responsiveWidth(4),
//     height: responsiveHeight(4),
//   },
//   messurementGenderMain: {
//     backgroundColor: primaryColor,
//     width: responsiveWidth(17),
//     height: responsiveHeight(3.5),
//     flex: 0,
//     paddingTop: responsiveHeight(0.3),
//     justifyContent: "center",
//     alignItems: "center",
//     borderWidth: 0,
//     borderRadius: responsiveHeight(0.5),
//   },
//   messurementGender: {
//     color: whiteColor,
//     fontFamily: "Regular",
//     fontSize: responsiveFontSize(1.7),
//   },
//   mainMeasurmentSection: {
//     flexDirection: "row",
//     justifyContent: "space-between",
//     alignItems: "center",
//     paddingVertical: responsiveHeight(1),
//     paddingHorizontal: responsiveHeight(1.6),
//     borderRadius: 6,
//     backgroundColor: whiteColor,
//     elevation: 1.5,
//     shadowOffset: { width: 5, height: 5, blur: 10 },
//     shadowOpacity: 1,
//     shadowRadius: 3,
//     shadowColor: secondaryColor,
//     marginBottom: responsiveHeight(1.4),
//     marginHorizontal: responsiveWidth(0.3),
//   },

//   //in add measerment dropdown css start
//   dressTypeSelectbutton: {
//     flexDirection: "row",
//     justifyContent: "space-between",
//     alignItems: "center",
//     padding: 10,
//     backgroundColor: lightGray,
//     borderRadius: 8,
//     marginVertical: 5,
//   },
//   selectedItemContainer: {
//     flexDirection: "row",
//     alignItems: "center",
//     flex: 1,
//     // marginHorizontal: responsiveWidth(3.5),
//   },
//   dropdownMeasericon: {
//     width: responsiveWidth(4),
//     height: responsiveHeight(4),
//   },
//   dropdownMeaserText: {
//     fontSize: responsiveFontSize(2),
//     marginHorizontal: responsiveWidth(3),
//     fontFamily: "Regular",
//   },
//   genderDropDownMeaserText: {
//     color: whiteColor,
//     fontSize: responsiveFontSize(1.6),
//     fontFamily: "Regular",
//     textAlign: "center",
//   },
//   mainDropdownMeaserIcon: {
//     width: responsiveWidth(11),
//     height: responsiveHeight(6),
//     backgroundColor: "#F2F2F2",
//     flex: 0,
//     justifyContent: "center",
//     alignItems: "center",
//     borderWidth: 0,
//     borderRadius: responsiveHeight(1),
//   },
//   mainMeasermentdropdown: {
//     position: "absolute",
//     top: responsiveHeight(7.5),
//     zIndex: 1000,
//     width: "100%",
//     height: "auto",
//     maxHeight: responsiveHeight(25),
//     backgroundColor: whiteColor,
//     borderRadius: 8,
//     elevation: 1.5,
//     shadowOffset: { width: 5, height: 5 },
//     shadowOpacity: 1,
//     shadowRadius: 3,
//     shadowColor: secondaryColor,
//   },
//   genderMale: {
//     backgroundColor: primaryColor,
//     paddingHorizontal: responsiveWidth(2.3),
//     flex: 0,
//     justifyContent: "center",
//     width: responsiveWidth(17),
//     height: responsiveHeight(3.5),
//     marginHorizontal: responsiveWidth(3),
//     borderWidth: 0,
//     borderRadius: responsiveHeight(0.5),
//   },
//   genderFeMale: {
//     backgroundColor: dangerColor,
//     paddingHorizontal: responsiveWidth(2.3),
//     flex: 0,
//     justifyContent: "center",
//     width: responsiveWidth(17),
//     height: responsiveHeight(3.5),
//     marginHorizontal: responsiveWidth(3),
//     borderWidth: 0,
//     borderRadius: responsiveHeight(0.5),
//   },
//   mainMeaserContainer: {
//     flexGrow: 1,
//   },
//   addMeasurementgrid: {
//     flexDirection: "row",
//     flexWrap: "wrap",
//     gap: responsiveWidth(3),
//     paddingBottom: responsiveHeight(3),
//   },
//   measuremntcard: {
//     width: "30%",
//     padding: responsiveWidth(3),
//     marginBottom: responsiveHeight(1),
//     borderRadius: 6,
//     backgroundColor: whiteColor,
//     elevation: 4,
//     shadowOffset: { width: 0, height: 5 },
//     shadowOpacity: 1,
//     shadowRadius: 3,
//     shadowColor: secondaryColor,
//     borderBottomColor: primaryColor,
//     borderBottomWidth: 1.5,
//   },
//   activeMeasermentcard: {
//     width: "30%",
//     padding: responsiveWidth(3),
//     marginBottom: responsiveHeight(1),
//     borderRadius: 6,
//     backgroundColor: whiteColor,
//     shadowColor: "#000000",
//     shadowOffset: {
//       width: 0,
//       height: 12,
//     },
//     shadowOpacity: 0.23,
//     shadowRadius: 12.81,
//     elevation: 16,
//     borderBottomColor: primaryColor,
//     borderBottomWidth: 2.5,
//   },
//   measerlabel: {
//     fontSize: responsiveFontSize(2),
//     color: "#333",
//     fontFamily: "Regular",
//   },
//   measeureinput: {
//     fontSize: responsiveFontSize(2.5),
//     fontFamily: "SemiBold",
//     color: "#333",
//     marginTop: responsiveHeight(1),
//   },

//   //order page
//   orderMain: {
//     borderRadius: 7,
//     backgroundColor: whiteColor,
//     elevation: 1.5,
//     shadowOffset: { width: 5, height: 5, blur: 10 },
//     shadowOpacity: 1,
//     shadowRadius: 7,
//     shadowColor: secondaryColor,
//     marginVertical: responsiveHeight(0.7),
//     marginLeft: responsiveWidth(1),
//     width: responsiveWidth(82),
//     minHeight: responsiveHeight(13),
//     padding: responsiveHeight(1.3),
//   },
//   orderRow: {
//     flexDirection: "row",
//   },
//   orderImageContainer: {
//     borderRadius: 6,
//     backgroundColor: lightGray,
//     flex: 0,
//     justifyContent: "center",
//     alignItems: "center",
//     width: responsiveWidth(20),
//     height: responsiveHeight(10.8),
//   },
//   orderTitleContainer: {
//     flexDirection: "row",
//     justifyContent: "space-between",
//     alignItems: "center",
//   },
//   orderTotalAmount: {
//     borderBottomColor: secondaryColor,
//     borderBottomWidth: responsiveWidth(0.5),
//     borderStyle: "dashed",
//     paddingBottom: responsiveHeight(0.5),
//   },
//   orderViewMain: {
//     flex: 0,
//     flexDirection: "row",
//     justifyContent: "center",
//     gap: responsiveWidth(2),
//     backgroundColor: whiteColor,
//     elevation: 1.5,
//     shadowOffset: { width: 5, height: 5, blur: 10 },
//     shadowOpacity: 1,
//     shadowRadius: 3,
//     paddingVertical: responsiveHeight(1.5),
//     shadowColor: secondaryColor,
//     borderRadius: responsiveWidth(1),
//     marginTop: responsiveHeight(2),
//   },
//   orderViewTotalAmount: {
//     marginTop: responsiveHeight(2),
//     backgroundColor: whiteColor,
//     elevation: 1.5,
//     shadowOffset: { width: 5, height: 5, blur: 10 },
//     shadowOpacity: 1,
//     shadowRadius: 3,
//     paddingHorizontal: responsiveWidth(3),
//     paddingVertical: responsiveHeight(1),
//     shadowColor: secondaryColor,
//     borderRadius: responsiveWidth(1),
//   },
//   orderViewDetails: {
//     marginTop: responsiveHeight(3),
//     flex: 0,
//     flexDirection: "row",
//     justifyContent: "space-between",
//     backgroundColor: lightGray,
//     paddingHorizontal: responsiveWidth(2),
//     paddingVertical: responsiveHeight(1),
//     marginHorizontal: responsiveWidth(0),
//     borderRadius: responsiveWidth(1),
//   },

//   //confirm page
//   confirmPageIconContainer: {
//     backgroundColor: primaryColor,
//     height: 60,
//     width: 60,
//     borderRadius: 100,
//     flexDirection: "row",
//     justifyContent: "center",
//     alignItems: "center",
//     shadowColor: secondaryColor,
//     shadowOffset: {
//       width: 0,
//       height: 18,
//     },
//     shadowOpacity: 0.3,
//     shadowRadius: 20,
//     elevation: 24,
//   },
//   // Payments
//   paymentsContainer: {
//     marginHorizontal: responsiveWidth(8),
//   },

//   paymentBox: {
//     marginTop: responsiveHeight(3),
//   },

//   totalpayment: {
//     paddingVertical: responsiveHeight(2),
//     paddingHorizontal: responsiveHeight(2),
//     borderRadius: 6,
//     backgroundColor: whiteColor,
//     elevation: 2.5,
//     shadowOffset: { width: 5, height: 5, blur: 10 },
//     shadowOpacity: 1,
//     shadowRadius: 3,
//     shadowColor: secondaryColor,
//   },

//   paymentHistory: {
//     paddingVertical: responsiveHeight(1),
//     paddingHorizontal: responsiveHeight(2),
//     borderRadius: 6,
//     backgroundColor: whiteColor,
//     elevation: 2.5,
//     shadowOffset: { width: 5, height: 5, blur: 10 },
//     shadowOpacity: 1,
//     shadowRadius: 3,
//     shadowColor: secondaryColor,
//     marginBottom: responsiveHeight(1.8),
//     marginTop: responsiveHeight(1),
//     marginHorizontal: responsiveWidth(0.2),
//   },
//   paymentOption: {
//     backgroundColor: "#EFF6EB",
//     paddingHorizontal: responsiveWidth(2.3),
//     flex: 0,
//     justifyContent: "center",
//     width: responsiveWidth(17),
//     height: responsiveHeight(3.5),
//     borderWidth: 0,
//     borderRadius: responsiveHeight(0.5),
//   },

//   paymentOptionText: {
//     color: primaryColor,
//     fontSize: responsiveFontSize(1.6),
//     fontFamily: "Bold",
//     textAlign: "center",
//   },

//   dashedBorder: {
//     borderBottomWidth: 1,
//     borderBottomColor: secondaryColor,
//     borderStyle: "dashed",
//     paddingBottom: responsiveHeight(1), // Optional: add some padding to the bottom for spacing
//   },
//   iconContainer: {
//     position: "absolute",
//     left: responsiveWidth(4),
//     top: responsiveHeight(5.5),
//   },
//   smalliconContainer: {
//     position: "absolute",
//     left: responsiveWidth(3),
//     top: responsiveHeight(5.2),
//   },

//   adddateinput: {
//     paddingVertical: responsiveHeight(1.5),
//     paddingLeft: responsiveWidth(13),
//     paddingRight: responsiveWidth(5),
//     backgroundColor: lightGray,
//     fontSize: responsiveFontSize(2),
//     fontFamily: "Regular",
//     borderRadius: 5,
//   },

//   Dateinput: {
//     paddingVertical: responsiveHeight(1),
//     paddingLeft: width * 0.1,
//     paddingRight: responsiveWidth(5),
//     backgroundColor: lightGray,
//     fontSize: responsiveFontSize(2),
//     fontFamily: "Regular",
//     borderRadius: 5,
//   },
//   Dateinputfield: {
//     width: responsiveWidth(37),
//   },
//   searchicon: {
//     position: "absolute",
//     top: responsiveHeight(5),
//     left: responsiveWidth(0),
//   },
//   disableInput: {
//     color: "black",
//   },

//   //generate pdf table
//   tablecontainer: {
//     borderColor: secondaryColor,
//     borderWidth: 0.5,
//     marginTop: responsiveHeight(2),
//   },
//   headerRow: {
//     flexDirection: "row",
//     backgroundColor: "#f2f2f2",
//     borderBottomWidth: 1,
//     borderBottomColor: "#ddd",
//   },
//   headerCell: {
//     paddingVertical: 5,
//     fontSize: responsiveFontSize(1),
//     fontFamily: "SemiBold",
//     borderRightWidth: 0.5,
//     borderRightColor: secondaryColor,
//     paddingLeft: responsiveWidth(1),
//   },
//   row: {
//     flexDirection: "row",
//     borderBottomWidth: 1,
//     borderBottomColor: "#ddd",
//   },
//   cell: {
//     paddingVertical: 5,
//     fontSize: responsiveFontSize(1),
//     borderRightWidth: 0.5,
//     fontFamily: "Regular",
//     borderRightColor: secondaryColor,
//     paddingLeft: responsiveWidth(1),
//   },
//   footerRow: {
//     flexDirection: "row",
//     backgroundColor: "#f2f2f2",
//     borderTopWidth: 1,
//     borderTopColor: "#ddd",
//   },
//   footerCell: {
//     paddingVertical: 5,
//     fontSize: responsiveFontSize(1),
//     borderRightWidth: 0.5,
//     fontFamily: "Regular",
//     borderRightColor: secondaryColor,
//     paddingLeft: responsiveWidth(1),
//   },
// });

// export {
//   styles,
//   primaryColor,
//   secondaryColor,
//   whiteColor,
//   lightGray,
//   dangerColor,
// };


import { StyleSheet, Dimensions } from "react-native";
import {
  responsiveFontSize,
  responsiveWidth,
  responsiveHeight,
} from "react-native-responsive-dimensions";
const primaryColor = "#56BC1F";
const secondaryColor = "gray";
const dangerColor = "#BC1F1F";
const whiteColor = "white";
const lightGray = "#f5f5f5";
const { width, height } = Dimensions.get('screen');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: whiteColor,
  },

  //bording
  rectangleContainer: {
    flexDirection: "row",
  },
  rectangle: {
    marginTop: responsiveHeight(10),
    right: 70,
    backgroundColor: "#D9D9D945",
    width: responsiveWidth(80),
    height: responsiveWidth(80),
    borderRadius: responsiveWidth(40),
  },
  image: {
    right: responsiveWidth(75),
    top: responsiveHeight(10),
    width: responsiveWidth(80),
    height: responsiveWidth(80),
  },
  content: {
    justifyContent: "center",
    alignItems: "center",
    marginTop: responsiveHeight(4),
  },
  headingtext: {
    color: primaryColor,
    fontSize: width * 0.076,
    letterSpacing: 0.3,
    fontFamily: "ExtraBold",
  },
  paratext: {
    marginTop: responsiveHeight(1),
    fontSize: width * 0.034,
    textAlign: "center",
    paddingHorizontal: 30,
    lineHeight: 20,
    fontFamily: "Regular",
  },
  dotcontainer: {
    marginTop: responsiveHeight(12),
    marginBottom: responsiveHeight(5),
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 100,
    backgroundColor: "#e6e6e6",
    marginHorizontal: 5,
  },
  active: {
    backgroundColor: primaryColor,
    color: whiteColor,
  },
  btngroup: {
    marginHorizontal: 10,
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    marginTop: responsiveHeight(8),
  },
  btntext: {
    color: primaryColor,
    letterSpacing: 1,
    paddingVertical: 10,
    paddingHorizontal: 50,
    borderRadius: 10,
    fontFamily: "SemiBold",
  },
  btnactive: {
    borderRadius: 10,
    shadowColor: primaryColor,
    shadowOffset: { width: 1, height: 1, blur: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 3,
    elevation: 5,
  },
  fullbtn: {
    fontFamily: "SemiBold",
    letterSpacing: 1,
    paddingVertical: 10,
    paddingHorizontal: 110,
    borderRadius: 10,
  },
  //login/registration
  loginHead: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingTop: responsiveHeight(2),
    paddingBottom: responsiveHeight(2),
  },
  loginHeadText: {
    // paddingLeft: responsiveWidth(15),
    paddingLeft: width * 0.12,
    marginTop: responsiveHeight(7),
    fontFamily: "Bold",
  },
  desctext: {
    fontSize: 14,
    lineHeight: responsiveHeight(2),
    fontFamily: "Regular",
  },
  loginimag: {
    height: 200,
    width: 160,
  },

  form: {
    marginHorizontal: responsiveWidth(8),
  },
  inputfield: {
    marginBottom: responsiveHeight(2.2),
  },
  label: {
    fontSize: 15,
    marginBottom: responsiveHeight(1),
    fontFamily: "Regular",
  },
  input: {
    paddingVertical: responsiveHeight(1.5),
    paddingHorizontal: responsiveWidth(5),
    backgroundColor: lightGray,
    fontSize: 15,
    fontFamily: "Regular",
    borderRadius: 5,
  },
  agreegroup: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "flex-end",
    marginRight: 20,
  },
  onlybtn: {
    padding: responsiveHeight(1.3),
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: primaryColor,
    borderRadius: responsiveWidth(1),
    marginBottom: responsiveHeight(1),
    shadowColor: primaryColor,
    shadowOffset: { width: 9, height: 9 },
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 5,
  },
  resendBtn: {
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  resendbtntext: {
    color: primaryColor,
  },
  onlybtntext: {
    color: whiteColor,
    fontSize: 17,
    letterSpacing: 0.5,
    fontFamily: "SemiBold",
  },
  bottom: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "flex-end",
    paddingTop: responsiveHeight(4),
  },
  link: {
    color: primaryColor,
    fontFamily: "Regular",
  },
  loginimag2: {
    height: responsiveHeight(30),
    marginRight: responsiveWidth(6),
    width: responsiveWidth(50),
    top: responsiveHeight(4),
  },
  //body parts
  flatlistheader: {
    paddingTop: responsiveHeight(4),
    paddingHorizontal: responsiveWidth(8),
    paddingBottom: responsiveHeight(2),
  },
  headername: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headernametext: {
    fontSize: width * 0.074,
    fontFamily: "Medium",
  },
  bodypartsbox: {
    paddingVertical: responsiveHeight(0.5),
    paddingHorizontal: responsiveHeight(0.1),
  },
  bodypartsboxshadow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: responsiveHeight(1),
    paddingHorizontal: responsiveHeight(1.6),
    borderRadius: 6,
    backgroundColor: whiteColor,
    elevation: 1.5,
    shadowOffset: { width: 5, height: 5, blur: 10 },
    shadowOpacity: 1,
    shadowRadius: 3,
    shadowColor: secondaryColor,
  },
  bodypartsboxtext: {
    fontFamily: "Regular",
    fontSize: responsiveFontSize(2.1),
  },
  rightsidebox: {
    flexDirection: "row",
    paddingTop: responsiveHeight(0.5),
  },
  //modal
  viewWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 0, 0, 0.2)",
  },
  modalView: {
    alignItems: "flex-start",
    justifyContent: "center",
    position: "absolute",
    width: "80%",
    elevation: 5,
    backgroundColor: whiteColor,
    borderRadius: 7,
    paddingVertical: responsiveHeight(2),
    paddingHorizontal: responsiveHeight(2),
  },
  modellabel: {
    fontSize: responsiveFontSize(2.1),
    opacity: 0.5,
    fontFamily: "Regular",
  },
  modalinput: {
    width: "100%",
    borderRadius: 5,
    paddingVertical: responsiveHeight(1),
    paddingHorizontal: responsiveHeight(1.6),
    borderColor: "rgba(0, 0, 0, 0.2)",
    borderWidth: 1,
    marginVertical: responsiveHeight(1.4),
    fontFamily: "Regular",
  },

  modelAlertbtn: {
    paddingVertical: responsiveHeight(1),
    paddingHorizontal: responsiveWidth(2),
    borderRadius: responsiveWidth(1.5),
    backgroundColor: primaryColor,
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },

  //addcomponent
  addmaincontainer: {
    position: "absolute",
    bottom: responsiveWidth(8),
    right: responsiveWidth(8),
    zIndex: 1000,
    shadowColor: secondaryColor,
    shadowOffset: {
      width: 0,
      height: 18,
    },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 24,
  },
  innercontainer: {
    backgroundColor: primaryColor,
    height: 60,
    width: 60,
    borderRadius: 100,
    position: "relative",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },

  //shop profile css start
  protop: {
    height: responsiveHeight(33),
    backgroundColor: lightGray,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  profilepic: {
    width: responsiveWidth(30),
    height: responsiveWidth(30),
    borderRadius: responsiveWidth(15),
  },
  profilelater: {
    width: responsiveWidth(30),
    height: responsiveWidth(30),
    borderRadius: responsiveWidth(15),
    backgroundColor: primaryColor,
    display: "flex",
  },
  profileTitle: {
    marginTop: responsiveHeight(2),
    fontFamily: "Regular",
    fontSize: responsiveFontSize(2.2),
  },
  titletext: {
    fontSize: responsiveFontSize(2.4),
    fontFamily: "Medium",
    marginTop: responsiveHeight(1),
  },
  spacebetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: responsiveHeight(2),
  },
  flexstart: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  backPRofileIcon: {
    backgroundColor: lightGray,
  },
  proicon: {
    backgroundColor: lightGray,
    paddingHorizontal: responsiveWidth(3),
    paddingVertical: responsiveWidth(3),
    borderRadius: responsiveWidth(1.5),
    marginRight: responsiveWidth(5),
  },
  prolistfont: {
    fontSize: responsiveFontSize(2.3),
    fontFamily: "Regular",
  },

  //edit profile css start
  profilelEditAvtar: {
    width: responsiveWidth(30),
    height: responsiveWidth(30),
    borderRadius: responsiveWidth(15),
    backgroundColor: lightGray,
    borderColor: primaryColor,
    borderWidth: 2.5,
    borderStyle: "dashed",
  },
  profilecameraicon: {
    textAlign: "center",
    fontSize: responsiveFontSize(2),
    backgroundColor: "black",
    color: "gray",
    marginTop: responsiveHeight(2),
    width: "20%",
    borderColor: "none",
    borderWidth: 0,
    borderRadius: responsiveWidth(3),
    padding: responsiveHeight(0.3),
    position: "absolute",
    bottom: responsiveHeight(-1.5),
    left: responsiveWidth(11.5),
  },

  //customer
  customerMain: {
    flex: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomColor: "#0000001A",
    paddingBottom: responsiveHeight(2),
    borderBottomWidth: 1,
    marginTop: responsiveHeight(2),
  },
  customerProfileImage: {
    width: responsiveWidth(12),
    height: responsiveWidth(12),
    borderRadius: responsiveWidth(15),
  },
  customerName: {
    fontSize: width * 0.048,
    fontFamily: "Medium",
  },
  headerwithline: {
    paddingTop: responsiveHeight(3),
    paddingBottom: responsiveHeight(1),
  },
  line70: {
    borderWidth: 0.5,
    borderColor: secondaryColor,
    width: responsiveWidth(60),
    marginLeft: responsiveWidth(20),
  },

  //dress
  dressContainermain: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: responsiveWidth(3),
    paddingHorizontal: responsiveWidth(8),
    paddingBottom: responsiveHeight(2),
  },
  dressFlatListContainermain: {
    paddingHorizontal: responsiveWidth(8),
    paddingBottom: responsiveHeight(2),
  },
  dressContainer: {
    backgroundColor: whiteColor,
    elevation: 1.5,
    shadowOffset: { width: 5, height: 5, blur: 10 },
    shadowOpacity: 1,
    shadowRadius: 3,
    shadowColor: secondaryColor,
    width: responsiveWidth(26),
    paddingTop: responsiveWidth(3),
    paddingHorizontal: responsiveHeight(1),
    borderRadius: 6,
  },
  imageContainer: {
    borderRadius: 6,
    backgroundColor: lightGray,
    flex: 0,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: responsiveHeight(0.6),
  },
  dressfileSelect: {
    width: responsiveWidth(6),
    height: responsiveHeight(13),
    borderColor: secondaryColor,
    borderWidth: 2,
    width: responsiveWidth(84),
    borderRadius: 4,
    borderStyle: "dashed",
    flex: 0,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  dressfileSelecttext: {
    fontFamily: "Regular",
    fontSize: responsiveFontSize(2),
  },
  dressbodypartsselected: {
    backgroundColor: primaryColor,
    width: responsiveWidth(5.4),
    height: responsiveHeight(2.6),
    flex: 0,
    alignItems: "center",
    borderRadius: 100,
    position: "absolute",
    justifyContent: "center",
    right: 0,
  },
  dressPartsdropdownMenu: {
    backgroundColor: whiteColor,
    width: responsiveWidth(37),
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    position: "absolute",
    top: responsiveHeight(8),
    right: responsiveWidth(4),
  },
  dressPartsdropdownItem: {
    paddingVertical: responsiveHeight(1),
  },
  dressPartsdropdownItemText: {
    fontSize: responsiveFontSize(2),
    fontFamily: "Regular",
  },
  //dressmodal
  modelicon: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: responsiveWidth(80),
    paddingVertical: responsiveHeight(3),
  },
  modelAlertlabel: {
    fontSize: responsiveFontSize(3),
    opacity: 0.7,
    textAlign: "center",
    width: responsiveWidth(80),
    marginTop: 5,
  },
  modelalertdec: {
    fontSize: responsiveFontSize(2.3),
    marginHorizontal: responsiveWidth(10),
    opacity: 0.6,
    textAlign: "center",
    width: responsiveWidth(60),
  },

  //measurement
  measurementSmallTitleMain: {
    marginHorizontal: responsiveWidth(8),
    marginTop: responsiveHeight(2),
  },
  measurementSmallTitle: {
    color: secondaryColor,
    fontSize: responsiveFontSize(1.5),
    fontFamily: "Regular",
  },

  measurementcateLine: {
    borderWidth: 0.2,
    borderColor: "#9f9f9f",
    width: responsiveWidth(30),
    marginTop: responsiveHeight(1),
  },
  measurementKurtaImageMain: {
    width: responsiveWidth(10.5),
    height: responsiveHeight(5),
    backgroundColor: "#F2F2F2",
    flex: 0,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 0,
    borderRadius: responsiveHeight(1),
  },
  measurementkurtaImage: {
    width: responsiveWidth(4),
    height: responsiveHeight(4),
  },
  messurementGenderMain: {
    backgroundColor: primaryColor,
    width: responsiveWidth(17),
    height: responsiveHeight(3.5),
    flex: 0,
    paddingTop: responsiveHeight(0.3),
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 0,
    borderRadius: responsiveHeight(0.5),
  },
  messurementGender: {
    color: whiteColor,
    fontFamily: "Regular",
    fontSize: responsiveFontSize(1.7),
  },
  mainMeasurmentSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: responsiveHeight(1),
    paddingHorizontal: responsiveHeight(1.6),
    borderRadius: 6,
    backgroundColor: whiteColor,
    elevation: 1.5,
    shadowOffset: { width: 5, height: 5, blur: 10 },
    shadowOpacity: 1,
    shadowRadius: 3,
    shadowColor: secondaryColor,
    marginBottom: responsiveHeight(1.4),
    marginHorizontal: responsiveWidth(0.3),
  },

  //in add measerment dropdown css start
  dressTypeSelectbutton: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
    backgroundColor: lightGray,
    borderRadius: 8,
    marginVertical: 5,
  },
  selectedItemContainer: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    // marginHorizontal: responsiveWidth(3.5),
  },
  dropdownMeasericon: {
    width: responsiveWidth(4),
    height: responsiveHeight(4),
  },
  dropdownMeaserText: {
    fontSize: responsiveFontSize(2),
    marginHorizontal: responsiveWidth(3),
    fontFamily: "Regular",
  },
  genderDropDownMeaserText: {
    color: whiteColor,
    fontSize: responsiveFontSize(1.6),
    fontFamily: "Regular",
    textAlign: "center",
  },
  mainDropdownMeaserIcon: {
    width: responsiveWidth(11),
    height: responsiveHeight(6),
    backgroundColor: "#F2F2F2",
    flex: 0,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 0,
    borderRadius: responsiveHeight(1),
  },
  mainMeasermentdropdown: {
    position: "absolute",
    top: responsiveHeight(7.5),
    zIndex: 1000,
    width: "100%",
    height: responsiveHeight(25),
    backgroundColor: whiteColor,
    borderRadius: 8,
    elevation: 1.5,
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 3,
    shadowColor: secondaryColor,
  },
  genderMale: {
    backgroundColor: primaryColor,
    paddingHorizontal: responsiveWidth(2.3),
    flex: 0,
    justifyContent: "center",
    width: responsiveWidth(17),
    height: responsiveHeight(3.5),
    marginHorizontal: responsiveWidth(3),
    borderWidth: 0,
    borderRadius: responsiveHeight(0.5),
  },
  genderFeMale: {
    backgroundColor: dangerColor,
    paddingHorizontal: responsiveWidth(2.3),
    flex: 0,
    justifyContent: "center",
    width: responsiveWidth(17),
    height: responsiveHeight(3.5),
    marginHorizontal: responsiveWidth(3),
    borderWidth: 0,
    borderRadius: responsiveHeight(0.5),
  },
  mainMeaserContainer: {
    flexGrow: 1,
  },
  addMeasurementgrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: responsiveWidth(3),
    paddingBottom: responsiveHeight(3),
  },
  measuremntcard: {
    width: "30%",
    padding: responsiveWidth(3),
    marginBottom: responsiveHeight(1),
    borderRadius: 6,
    backgroundColor: whiteColor,
    elevation: 4,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 3,
    shadowColor: secondaryColor,
    borderBottomColor: primaryColor,
    borderBottomWidth: 1.5,
  },
  activeMeasermentcard: {
    width: "30%",
    padding: responsiveWidth(3),
    marginBottom: responsiveHeight(1),
    borderRadius: 6,
    backgroundColor: whiteColor,
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.23,
    shadowRadius: 12.81,
    elevation: 16,
    borderBottomColor: primaryColor,
    borderBottomWidth: 2.5,
  },
  measerlabel: {
    fontSize: responsiveFontSize(2),
    color: "#333",
    fontFamily: "Regular",
  },
  measeureinput: {
    fontSize: responsiveFontSize(2.5),
    fontFamily: "SemiBold",
    color: "#333",
    marginTop: responsiveHeight(1),
  },

  //order page
  orderMain: {
    borderRadius: 7,
    backgroundColor: whiteColor,
    elevation: 1.5,
    shadowOffset: { width: 5, height: 5, blur: 10 },
    shadowOpacity: 1,
    shadowRadius: 7,
    shadowColor: secondaryColor,
    marginVertical: responsiveHeight(0.7),
    marginLeft: responsiveWidth(1),
    width: responsiveWidth(82),
    minHeight: responsiveHeight(13),
    padding: responsiveHeight(1.3),
  },
  orderRow: {
    flexDirection: "row",
  },
  orderImageContainer: {
    borderRadius: 6,
    backgroundColor: lightGray,
    flex: 0,
    justifyContent: "center",
    alignItems: "center",
    width: responsiveWidth(20),
    height: responsiveHeight(10.8),
  },
  orderTitleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  orderTotalAmount: {
    borderBottomColor: secondaryColor,
    borderBottomWidth: responsiveWidth(0.5),
    borderStyle: "dashed",
    paddingBottom: responsiveHeight(0.5),
  },
  orderViewMain: {
    flex: 0,
    flexDirection: "row",
    justifyContent: "center",
    gap: responsiveWidth(2),
    backgroundColor: whiteColor,
    elevation: 1.5,
    shadowOffset: { width: 5, height: 5, blur: 10 },
    shadowOpacity: 1,
    shadowRadius: 3,
    paddingVertical: responsiveHeight(1.5),
    shadowColor: secondaryColor,
    borderRadius: responsiveWidth(1),
    marginTop: responsiveHeight(2),
  },
  orderViewTotalAmount: {
    marginTop: responsiveHeight(2),
    backgroundColor: whiteColor,
    elevation: 1.5,
    shadowOffset: { width: 5, height: 5, blur: 10 },
    shadowOpacity: 1,
    shadowRadius: 3,
    paddingHorizontal: responsiveWidth(3),
    paddingVertical: responsiveHeight(1),
    shadowColor: secondaryColor,
    borderRadius: responsiveWidth(1),
  },
  orderViewDetails: {
    flex: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: lightGray,
    paddingHorizontal: responsiveWidth(2),
    paddingVertical: responsiveHeight(1),
    marginHorizontal: responsiveWidth(0),
    borderRadius: responsiveWidth(1),
  },

  //confirm page
  confirmPageIconContainer: {
    backgroundColor: primaryColor,
    height: 60,
    width: 60,
    borderRadius: 100,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: secondaryColor,
    shadowOffset: {
      width: 0,
      height: 18,
    },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 24,
  },
  // Payments
  paymentsContainer: {
    marginHorizontal: responsiveWidth(8),
  },

  paymentBox: {
    marginTop: responsiveHeight(3),
  },

  totalpayment: {
    paddingVertical: responsiveHeight(2),
    paddingHorizontal: responsiveHeight(2),
    borderRadius: 6,
    backgroundColor: whiteColor,
    elevation: 2.5,
    shadowOffset: { width: 5, height: 5, blur: 10 },
    shadowOpacity: 1,
    shadowRadius: 3,
    shadowColor: secondaryColor,
  },

  paymentHistory: {
    paddingVertical: responsiveHeight(1),
    paddingHorizontal: responsiveHeight(2),
    borderRadius: 6,
    backgroundColor: whiteColor,
    elevation: 2.5,
    shadowOffset: { width: 5, height: 5, blur: 10 },
    shadowOpacity: 1,
    shadowRadius: 3,
    shadowColor: secondaryColor,
    marginBottom: responsiveHeight(1.8),
    marginTop: responsiveHeight(1),
    marginHorizontal: responsiveWidth(0.2),
  },
  paymentOption: {
    backgroundColor: "#EFF6EB",
    paddingHorizontal: responsiveWidth(2.3),
    flex: 0,
    justifyContent: "center",
    width: responsiveWidth(17),
    height: responsiveHeight(3.5),
    borderWidth: 0,
    borderRadius: responsiveHeight(0.5),
  },

  paymentOptionText: {
    color: primaryColor,
    fontSize: responsiveFontSize(1.6),
    fontFamily: "Bold",
    textAlign: "center",
  },

  dashedBorder: {
    borderBottomWidth: 1,
    borderBottomColor: secondaryColor,
    borderStyle: "dashed",
    paddingBottom: responsiveHeight(1), // Optional: add some padding to the bottom for spacing
  },
  iconContainer: {
    position: "absolute",
    left: responsiveWidth(4),
    top: responsiveHeight(5.5),
  },
  smalliconContainer: {
    position: "absolute",
    left: responsiveWidth(3),
    top: responsiveHeight(5.2),
  },

  adddateinput: {
    paddingVertical: responsiveHeight(1.5),
    paddingLeft: responsiveWidth(13),
    paddingRight: responsiveWidth(5),
    backgroundColor: lightGray,
    fontSize: responsiveFontSize(2),
    fontFamily: "Regular",
    borderRadius: 5,
  },

  Dateinput: {
    paddingVertical: responsiveHeight(1),
    paddingLeft: width * 0.1,
    paddingRight: responsiveWidth(5),
    backgroundColor: lightGray,
    fontSize: responsiveFontSize(2),
    fontFamily: "Regular",
    borderRadius: 5,
  },
  Dateinputfield: {
    width: responsiveWidth(37),
  },
  searchicon: {
    position: "absolute",
    top: responsiveHeight(5),
    left: responsiveWidth(0),
  },
  disableInput: {
    color: "black",
  },

  //generate pdf table
  tablecontainer: {
    borderColor: secondaryColor,
    borderWidth: 0.5,
    marginTop: responsiveHeight(2),
  },
  headerRow: {
    flexDirection: "row",
    backgroundColor: "#f2f2f2",
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  headerCell: {
    paddingVertical: 5,
    fontSize: responsiveFontSize(1),
    fontFamily: "SemiBold",
    borderRightWidth: 0.5,
    borderRightColor: secondaryColor,
    paddingLeft: responsiveWidth(1),
  },
  row: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  cell: {
    paddingVertical: 5,
    fontSize: responsiveFontSize(1),
    borderRightWidth: 0.5,
    fontWeight: 'bold',
    fontFamily: "Regular",
    borderRightColor: secondaryColor,
    paddingLeft: responsiveWidth(1),
  },
  footerRow: {
    flexDirection: "row",
    backgroundColor: "#f2f2f2",
    borderTopWidth: 1,
    borderTopColor: "#ddd",
  },
  footerCell: {
    paddingVertical: 5,
    fontSize: responsiveFontSize(1),
    borderRightWidth: 0.5,
    fontFamily: "Regular",
    borderRightColor: secondaryColor,
    paddingLeft: responsiveWidth(1),
  },
});

export {
  styles,
  primaryColor,
  secondaryColor,
  whiteColor,
  lightGray,
  dangerColor,
};

